### ISSUE TITLE
Timeout too short

### ISSUE THREAD

**Issue by beandaschu** [JKISoftware/JKI-REST-Client#10]
Is there a possibility to change the timeout for the http get request?

**Comment by jimkring** [comment]
That sounds totally reasonable. Will take a look at it.
-- 
Jim Sent from my mobile.

**Comment by jimkring** [comment]
Hi @beandaschu,

You can change the timeout before each GET call using the Write Timeout accessor, as shown in this snippet.

![http get rest with timeout](https://user-images.githubusercontent.com/381432/52813159-06bad280-304e-11e9-8a84-d9d870875ee3.png)

That VI is in the Accessors sub-palette.

![image](https://user-images.githubusercontent.com/381432/52813272-441f6000-304e-11e9-8da7-c1cbe2d36507.png)

Let me know how that works for you.

**Comment by carlodri** [comment]
just wondering: why not make this simpler and add (also) a timeout terminal on each methods' VI? Just like the native NI HTTP method VIs.

**Comment by carlodri** [comment]
by the way, thanks for the great framework, it's really nice to have proper handling of RESTful architectures.

**Comment by jimkring** [comment]
@carlodri I agree that it would be simpler to add a timeout terminal on each of the methods, that overrides the default timeout (set on the object data/wire).  I'm thinking that an implementation like this would work well.

I think using a timeout of "0" as the signal to use the object's value would be good (as opposed to "-1" which typically means "No Timeout") since a timeout value of "0" isn't really useful for anything practical (any HTTP transaction will take a time > 0).

Please let me know if I'm missing anything or you have any suggestions.

![image](https://user-images.githubusercontent.com/381432/52879206-6af39a00-3113-11e9-963a-2a0cb6b06cbc.png)

![image](https://user-images.githubusercontent.com/381432/52879210-6e872100-3113-11e9-836d-95e4096d2cdf.png)

**Comment by jimkring** [comment]
I've created a feature enhancement issue for this, here, where it can be further discussed: https://github.com/JKISoftware/JKI-REST-Client/issues/11

**Comment by jimkring** [comment]
Implemented in [1.3.2](https://github.com/JKISoftware/JKI-HTTP-REST-Client/releases/tag/1.3.2) and available for [download with VIPM](https://resources.jki.net/http-rest-client-for-labview).

**Comment by beandaschu** [comment]
Hey Thanks a lot for helping me and solving the problem

**Comment by carlodri** [comment]
thanks @jimkring!

**Comment by jimkring** [comment]
You're welcome @beandaschu and @carlodri. I appreciate both of your feedback and help with testing.
